// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs env.go
package hik_vision_sdk

type (
	SDKCfgAbility struct {
		EnumMaxLoginUsersNum uint32
		EnumMaxAlarmNum      uint32
		ByRes                [64]uint8
	}
	SDKCfgSDKPath struct {
		SPath [256]int8
		ByRes [128]uint8
	}

	Package struct {
		data []byte
	}
)
