// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs env.go
package hik_vision_sdk

type (
	SDKCfgAbility struct {
		EnumMaxLoginUsersNum uint32
		EnumMaxAlarmNum      uint32
		ByRes                [64]uint8
	}
	SDKCfgSDKPath struct {
		SPath [256]int8
		ByRes [128]uint8
	}

	DeviceInfo struct {
		SSerialNumber     [48]uint8
		ByAlarmInPortNum  uint8
		ByAlarmOutPortNum uint8
		ByDiskNum         uint8
		ByDVRType         uint8
		ByChanNum         uint8
		ByStartChan       uint8
	}

	Package struct {
		Data []byte
	}
)
